name: Compile on all platforms

on:
  pull_request:
    branches:
      - main

jobs:
  windows:
    name: Compile Windows
    runs-on: windows-11-vs2026-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run build script
        shell: pwsh
        run: |
          ./build.bat

  linux:
    name: Compile Linux
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl3-dev pkg-config

      - name: Run build script
        run: |
          ./build.sh
